printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "all"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "always"
proseWrap: "preserve"
htmlWhitespaceSensitivity: "css"
vueIndentScriptAndStyle: true
endOfLine: "lf"
embeddedLanguageFormatting: "auto"